# Universal Sentence Encoding

- Google released this pre-trained Universal Sentence Encoder, which supports 16 languages, including traditional Chinese!!
- [Universal Sentence Encoder](https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3)
- This universal encoding allows us to compute the semantic similarities between sentences in one language as well as sentences across different languages



In [1]:
!pip3 install tensorflow_text>=2.0.0rc0

In [2]:
import tensorflow_hub as hub
import numpy as np
import tensorflow_text


In [3]:
# Some texts of different lengths.
chinese_sentences = ["今天天氣還不錯",
                     "我昨天去那家店買本書",
                     "他的名字是奶奶取的",
                     "這天氣也太美妙了"]

english_sentences = ["It's nice today",
                     "I bought a book at the store yesterday",
                     "His granny gave him this beautiful name",
                     "The weather is just lovely"]

embed = hub.load("https://tfhub.dev/google/universal-sentence-encoder-multilingual-large/3")

In [4]:
# Compute embeddings.

ch_result = embed(chinese_sentences)
en_result = embed(english_sentences)
# Compute similarity matrix. Higher score indicates greater similarity.
similarity_matrix_ch = np.inner(ch_result, ch_result)
similarity_matrix_en = np.inner(en_result, en_result)
similarity_matrix_ce = np.inner(ch_result, en_result)

In [5]:
print(similarity_matrix_ch)

[[1.0000001  0.24749225 0.06170724 0.89655745]
 [0.24749225 1.0000002  0.03579599 0.16391829]
 [0.06170724 0.03579599 0.9999998  0.06162469]
 [0.89655745 0.16391829 0.06162469 0.9999999 ]]


In [6]:
print(similarity_matrix_en)

[[1.0000001  0.2479216  0.17508116 0.50977063]
 [0.2479216  1.0000002  0.11042947 0.08615555]
 [0.17508116 0.11042947 1.0000002  0.20739618]
 [0.50977063 0.08615555 0.20739618 1.0000002 ]]


In [7]:
print(similarity_matrix_ce)

[[0.7144892  0.22732086 0.09561004 0.59900224]
 [0.18444145 0.8110584  0.07247735 0.08440702]
 [0.12534358 0.04717048 0.73678607 0.09883476]
 [0.6257671  0.13114104 0.12800807 0.72508615]]
